import math


#Evaluate the total structural weight penalty and of adding a transverse canard port to a drone fuselage.
def analyze_canard_structural_impact(
    mtow_kg=100.0,                   # Maximum Takeoff Weight of the drone [kg]
    max_g_load=6.0,                  # Maximum g-load based on Aerobatic CS-23 classification
    canard_lift_fraction=0.20,       # Fraction of total lift generated by the canard in relation to main wing.
    fuselage_length=3.0,             # Total length of the fuselage [m]
    cg_location=1.5,                 # Distance from nose to CG [m]
    tip_to_canard_distance=0.5,      # Distance from tip of the fuselage to canard port [m]
    fuselage_diameter=0.15,          # Fuselage diameter [m]
    minimum_thickness=0.001,         # Minimum manufacturing thickness [m] - 1mm default
    skin_density=1600.0,             # Skin density [kg/m^3] - CFRP: 1600, Aluminum 7075-T6: 2810.0
    skin_yield_strength=600e6,       # Skin yield strength [Pa] CFRP Quasi-isotropic: 600e6, Aluminum 7075-T6: 500e6
    safety_factor=1.5,
    rod_outer_diameter=0.02,         # Diameter of the hollow rod canard port [m]
    rod_wall_thickness=0.002,        # Wall thickness of the hollow rod [m]
    rod_density=2810.0,              # Density of hollow rod material [kg/m^3] - CFRP: 1600, Aluminum 7075-T6: 2810.0
    reinforcement_diameter=2.0,      # Multiplier for the diameter of the local hole reinforcement compared to the canard cutout diameter (e.g. 2.0 means the reinforcement circle diameter is 2x the cutout diameter)
    thickness_multiplier = 3.0       # Multiplier for the thickness of the local hole reinforcement compared to the required skin thickness (e.g. 3.0 means the local hole reinforcement is 3x thicker than the required skin thickness)
):
    
    distance_to_canard = cg_location - tip_to_canard_distance # Distance from CG to canard port [m]
     
    # Aerodynamic Loads & Bending Moment
    
    total_lift = mtow_kg * max_g_load * 9.81 # Total lift in Newtons
    canard_force = total_lift * canard_lift_fraction # Force on the canard in Newtons
    max_bending_moment = canard_force * distance_to_canard # Bending moment at the canard in Nm
    radius = fuselage_diameter / 2.0 # Radius of the fuselage in meters
    

    # No Port Front-half Fuselage Mass
       
    baseline_fronthalf_volume = 2 * math.pi * radius * minimum_thickness * distance_to_canard
    baseline_fronthalf_mass = baseline_fronthalf_volume * skin_density
   
    # Skin Thickness Sizing (Bending vs. Minimum Thickness)
    
    bending_thickness = (max_bending_moment * safety_factor) / (math.pi * (radius**2) * skin_yield_strength) # Thickness required to resist bending loads with safety factor
    
    required_thickness = max(bending_thickness, minimum_thickness) # Final required thickness is the maximum between bending load thickness and manufacturing minimum
    design_driven_by = "Bending Loads" if bending_thickness > minimum_thickness else "Minimum Thickness"
        
    # Global Weight Penalty (Thickening the front half of the fuselage)
    
    delta_thickness = required_thickness - minimum_thickness # If the required thickness is greater than the minimum, this is the additional thickness added
    volume_fronthalf_reinforcement = 2 * math.pi * radius * delta_thickness * distance_to_canard # Volume of the front half reinforcement
    mass_fronthalf_reinforcement = volume_fronthalf_reinforcement * skin_density # Mass of the front half reinforcement
    
    
    # Local Weight Penalty (cutout vs hole reinforcements)

    cutout_area = math.pi * (rod_outer_diameter / 2)**2
    
    mass_removed_skin = 2 * cutout_area * required_thickness * skin_density # Mass of the skin removed for the cutout (both sides of the fuselage)
    
    mass_local_reinforcement = (math.pi*((rod_outer_diameter * reinforcement_diameter)/2)**2 - math.pi*(rod_outer_diameter/2)**2) * (required_thickness * (thickness_multiplier-1)) * skin_density #  Week 5-2 of SAD lecture slides page 18. 
    
    # Mass of canard port hollow rod

    rod_inner_diameter = rod_outer_diameter - (2 * rod_wall_thickness) 
    rod_cross_section = math.pi * ((rod_outer_diameter / 2)**2 - (rod_inner_diameter / 2)**2)
    mass_rod = rod_cross_section * fuselage_diameter * rod_density
    

    # Final Mass Penalty Calculation

    net_weight_penalty = mass_fronthalf_reinforcement + mass_local_reinforcement + mass_rod - mass_removed_skin
    new_total_nose_mass = baseline_fronthalf_mass + net_weight_penalty
    
    percentage_increase_local = (net_weight_penalty / baseline_fronthalf_mass) * 100
    percentage_increase_mtow = (net_weight_penalty / mtow_kg) * 100
    
    return {
        "Aerodynamics - Canard Force (N)": round(canard_force, 2),
        "Aerodynamics - Maximum Bending Moment (Nm)": round(max_bending_moment, 2),
        "Sizing - Bending Minimum Thickness (mm)": round(bending_thickness * 1000, 3),
        "Sizing - Actual Sized Thickness (mm)": round(required_thickness * 1000, 3),
        "Sizing - Design Driven By": design_driven_by,
        "Mass - Baseline 'Clean' Nose (kg)": round(baseline_fronthalf_mass, 4),
        "Penalty - Global Nose Thickening (kg)": round(mass_fronthalf_reinforcement, 4),
        "Penalty - Local Hole Doublers (kg)": round(mass_local_reinforcement, 4),
        "Penalty - Canard Port Hollow Rod (kg)": round(mass_rod, 4),
        "Savings - Removed Skin (kg)": round(-mass_removed_skin, 4),
        "NET TOTAL WEIGHT PENALTY (kg)": round(net_weight_penalty, 4),
        "Mass - New Total Front-half Mass (kg)": round(new_total_nose_mass, 4),
        "Significance - Local (% increase to front-half)": f"{round(percentage_increase_local, 1)} %",
        "Significance - Global (% increase to MTOW)": f"{round(percentage_increase_mtow, 2)} %"
    }