import math


#Evaluate the total structural weight penalty of the empennage.

def analyze_empennage_structural_impact(
    mtow_kg=100.0,                   # Maximum Takeoff Weight of the drone [kg]
    max_g_load=6.0,                  # Maximum g-load based on Aerobatic CS-23 classification
    empennage_lift_fraction=0.20,     # Fraction of total lift generated by the empennage in relation to main wing.
    fuselage_length=3.0,             # Total length of the fuselage [m]
    cg_location=1.5,                 # Distance from nose to CG [m]
    fuselage_diameter=0.15,          # Fuselage diameter [m]
    minimum_thickness=0.001,         # Minimum manufacturing thickness [m] - 1mm default
    skin_density=1600.0,             # Skin density [kg/m^3] - CFRP: 1600, Aluminum 7075-T6: 2810.0
    skin_yield_strength=600e6,       # Skin yield strength [Pa] CFRP Quasi-isotropic: 600e6, Aluminum 7075-T6: 500e6
    safety_factor=1.5,
    ):

    empennage_location = fuselage_length - 0.3 # Assuming the empennage is located 30cm from the tail end of the fuselage
    distance_to_empennage = empennage_location - cg_location # Distance from CG to empennage [m]
     
    # Aerodynamic Loads & Bending Moment
    
    total_lift = mtow_kg * max_g_load * 9.81 # Total lift in Newtons
    empennage_force = total_lift * empennage_lift_fraction # Force on the empennage in Newtons
    max_bending_moment = empennage_force * distance_to_empennage # Bending moment at the empennage in Nm
    radius = fuselage_diameter / 2.0 # Radius of the fuselage in meters
    
    # Skin Thickness Sizing (Bending vs. Minimum Thickness)
    
    bending_thickness = (max_bending_moment * safety_factor) / (math.pi * (radius**2) * skin_yield_strength) # Thickness required to resist bending loads with safety factor
    
    required_thickness = max(bending_thickness, minimum_thickness) # Final required thickness is the maximum between bending load thickness and manufacturing minimum
    design_driven_by = "Bending Loads" if bending_thickness > minimum_thickness else "Minimum Thickness"
        
    # Baseline minimum weight of the aft half of the fuselage
    baseline_afthalf_volume = 2 * math.pi * radius * minimum_thickness * distance_to_empennage
    baseline_afthalf_mass = baseline_afthalf_volume * skin_density
    
    
    # Global Weight Penalty (Thickening the front half of the fuselage)
    
    delta_thickness = required_thickness - minimum_thickness # If the required thickness is greater than the minimum, this is the additional thickness added
    volume_aft_reinforcement = 2 * math.pi * radius * delta_thickness * distance_to_empennage # Volume of the front half reinforcement
    mass_aft_reinforcement = volume_aft_reinforcement * skin_density # Mass of the front half reinforcement
    
    
    # Final Mass Calculation

    net_weight_penalty = mass_aft_reinforcement
    new_total_aft_mass = baseline_afthalf_mass + net_weight_penalty
    
    percentage_increase_local = (net_weight_penalty / baseline_afthalf_mass) * 100
    percentage_increase_mtow = (net_weight_penalty / mtow_kg) * 100
    
    return {
        "Aerodynamics - Empennage Force (N)": round(empennage_force, 2),
        "Aerodynamics - Maximum Bending Moment (Nm)": round(max_bending_moment, 2),
        "Sizing - Bending Minimum Thickness (mm)": round(bending_thickness * 1000, 3),
        "Sizing - Actual Sized Thickness (mm)": round(required_thickness * 1000, 3),
        "Sizing - Design Driven By": design_driven_by,
        "Mass - Baseline Aft-half (kg)": round(baseline_afthalf_mass, 4),
        "Penalty - Bending Reinforcement Aft-half Thickening (kg)": round(mass_aft_reinforcement, 4),
        "NET TOTAL WEIGHT PENALTY (kg)": round(net_weight_penalty, 4),
        "Mass - New Total Aft-half Mass (kg)": round(new_total_aft_mass, 4),
        "Significance - Local (% increase to aft-half)": f"{round(percentage_increase_local, 1)} %",
        "Significance - Global (% increase to MTOW)": f"{round(percentage_increase_mtow, 2)} %"
    }