# Make everything an input, ask AI to generate it.


#constants
g = 9.81                        # Gravitational acceleration [m/s^2]

Aluminum = [2810.0, 500e6]       # Aluminum 7075-T6 properties: Density [kg/m^3], Yield Strength [Pa]
CFRP = [1600.0, 600e6]           # CFRP Quasi-isotropic properties: Density [kg/m^3], Yield Strength [Pa]



#Load parameters
mtow=100.0                      # Maximum Takeoff Weight of the drone [kg]
max_g_load=6.0                  # Maximum g-load based on Aerobatic CS-23 classification
safety_factor=1.5               # Safety factor for structural design
cruise_speed=15.0               # Cruise speed of the drone [m/s]


W = mtow * g * max_g_load * safety_factor           # Total weight force under max G-load [N]



#Fuselage parameters
fuselage_length=3.0                               # Total length of the fuselage [m]
fuselage_diameter=0.15                            # Fuselage diameter [m]
minimum_thickness=0.001                           # Minimum manufacturing thickness [m] - 1mm default
skin_material_choice = CFRP                       # Material choice for the fuselage skin ("CFRP" or "Aluminum")
skin_density=skin_material_choice[0]              # Skin density [kg/m^3] - CFRP: 1600, Aluminum 7075-T6: 2810.0
skin_yield_strength=skin_material_choice[1]       # Skin yield strength [Pa] CFRP Quasi-isotropic: 600e6, Aluminum 7075-T6: 500e6


fuselage_radius = fuselage_diameter / 2             # Fuselage radius [m]

#Main wing parameters
wingspan=3.0                                       # Wingspan [m]
Aspect_ratio=25.0                                  # Wing aspect ratio
fraction_root_thickness= 0.12                      # Fraction of the chord that defines the root thickness of the wing
z_location_mainwing=fuselage_radius                # Z-location of top part of the main wing [m]

wing_material_choice = CFRP                        # Material choice for the wing structure ("CFRP" or "Aluminum")
wing_density=wing_material_choice[0]               # Wing material density [kg/m^3]
wing_yield_strength=wing_material_choice[1]        # Wing material yield strength [Pa]
wing_skin_thickness=0.002                          # Thickness of the wing skin [m]

chord_length = (wingspan / Aspect_ratio)           # Chord length at the root of the wing [m]
t_wing = fraction_root_thickness * chord_length    # Root thickness of the wing [m]
wing_I_xx = ((chord_length * t_wing**3)/12)-((chord_length-wing_skin_thickness*2)*(t_wing-wing_skin_thickness*2)**3)/12                 # Moment of inertia of the wing cross-section [m^4]


if z_location_mainwing > fuselage_radius or z_location_mainwing < -fuselage_radius:
    raise ValueError("Warning: Main wing placed outside of fuselage. Change z_location_mainwing to be within fuselage radius.")
if z_location_mainwing - t_wing < -fuselage_radius:
    raise ValueError("Warning: Main wing extends below the bottom of the fuselage. Increase z_location_mainwing.")




#Locations (m from nose)
cg_loc=1.5                      # Distance from nose to CG [m]
canard_loc=0.5                  # Distance from tip of the fuselage to canard port [m]
main_wing_loc=1.8               # Distance from nose to main wing [m]
empennage_loc=2.7               # Distance from nose to empennage [m]
nose_gear_loc=0.3               # Distance from nose to nose gear [m]
main_gear_loc=2.0               # Distance from nose to main gear [m]



#Canard parameters
canard_lift_fraction=0.2                      # Fraction of total lift generated by the canard in relation to main wing.
canard_rod_material= Aluminum                  # Material choice for the canard port hollow rod
rod_outer_diameter=0.02                        # Diameter of the hollow rod canard port [m]
rod_wall_thickness=0.002                       # Wall thickness of the hollow rod [m]
rod_density=canard_rod_material[0]             # Density of hollow rod material [kg/m^3] - CFRP: 1600, Aluminum 7075-T6: 2810.0
reinforcement_diameter=2.0                     # Multiplier for the diameter of the local hole reinforcement compared to the canard cutout diameter (e.g. 2.0 means the reinforcement circle diameter is 2x the cutout diameter)
thickness_multiplier = 3.0                     # Multiplier for the thickness of the local hole reinforcement compared to the required skin thickness (e.g. 3.0 means the local hole reinforcement is 3x thicker than the required skin thickness)
z_location_canard = -0.05                       # Z-location of top part of the canard [m]

if z_location_canard > fuselage_radius or z_location_canard < -fuselage_radius:
    raise ValueError("Warning: Canard placed outside of fuselage. Change z_location_canard to be within fuselage radius.")


#Analysis parameters
resolution = 501                                    # Higher resolution for integration accuracy
