import math


# Evaluate the total structural weight penalty of the fuselage due to the main wing.

def analyze_main_wing_structural_impact(
    mtow=100.0,                   # Maximum Takeoff Weight of the drone [kg]
    max_g_load=6.0,                  # Maximum g-load based on Aerobatic CS-23 classification
    main_wing_lift_fraction=1,       # Fraction of total lift generated by the main wing.
    fuselage_length=3.0,             # Total length of the fuselage [m]
    cg_location=1.5,                 # Distance from nose to CG [m]
    main_wing_location=1.8,          # Distance from nose to main wing attachment [m]
    fuselage_diameter=0.15,          # Fuselage diameter [m]
    minimum_thickness=0.001,         # Minimum manufacturing thickness [m] - 1mm default
    skin_density=1600.0,             # Skin density [kg/m^3] - CFRP: 1600, Aluminum 7075-T6: 2810.0
    skin_yield_strength=600e6,       # Skin yield strength [Pa] CFRP Quasi-isotropic: 600e6, Aluminum 7075-T6: 500e6
    safety_factor=1.5,
    ):

    distance_to_main_wing = main_wing_location - cg_location # Distance from CG to main wing [m]
     
    # Aerodynamic Loads & Bending Moment
    
    total_lift = mtow * max_g_load * 9.81 # Total lift in Newtons
    main_wing_force = total_lift * main_wing_lift_fraction # Force on the main wing in Newtons
    max_bending_moment = main_wing_force * distance_to_main_wing # Bending moment at fuselage due to main wing in Nm
    radius = fuselage_diameter / 2.0 #  Radius of the fuselage in meters
    
    # Skin Thickness Sizing (Bending vs. Minimum Thickness)
    
    bending_thickness = (max_bending_moment * safety_factor) / (math.pi * (radius**2) * skin_yield_strength) # Thickness required to resist bending loads with safety factor
    
    required_thickness = max(bending_thickness, minimum_thickness) # Final required thickness is the maximum between bending load thickness and manufacturing minimum
    design_driven_by = "Bending Loads" if bending_thickness > minimum_thickness else "Minimum Thickness"
        
    # Baseline minimum weight of the fuselage section from CG to main wing
    baseline_fuselage_volume = 2 * math.pi * radius * minimum_thickness * distance_to_main_wing
    baseline_fuselage_mass = baseline_fuselage_volume * skin_density
    
    
    # Global Weight Penalty (Thickening the fuselage section)
    
    delta_thickness = required_thickness - minimum_thickness # If the required thickness is greater than the minimum, this is the additional thickness added
    volume_reinforcement = 2 * math.pi * radius * delta_thickness * distance_to_main_wing # Volume of the fuselage reinforcement
    mass_reinforcement = volume_reinforcement * skin_density # Mass of the fuselage reinforcement
    
    
    # Final Mass Calculation

    net_weight_penalty = mass_reinforcement
    new_total_fuselage_mass = baseline_fuselage_mass + net_weight_penalty
    
    percentage_increase_local = (net_weight_penalty / baseline_fuselage_mass) * 100
    percentage_increase_mtow = (net_weight_penalty / mtow) * 100
    
    return {
        "Aerodynamics - Main Wing Force (N)": round(main_wing_force, 2),
        "Aerodynamics - Maximum Bending Moment (Nm)": round(max_bending_moment, 2),
        "Sizing - Bending Minimum Thickness (mm)": round(bending_thickness * 1000, 3),
        "Sizing - Actual Sized Thickness (mm)": round(required_thickness * 1000, 3),
        "Sizing - Design Driven By": design_driven_by,
        "Mass - Baseline Fuselage Section (kg)": round(baseline_fuselage_mass, 4),
        "Penalty - Bending Reinforcement Fuselage Thickening (kg)": round(mass_reinforcement, 4),
        "NET TOTAL WEIGHT PENALTY (kg)": round(net_weight_penalty, 4),
        "Mass - New Total Fuselage Section Mass (kg)": round(new_total_fuselage_mass, 4),
        "Significance - Local (% increase to fuselage section)": f"{round(percentage_increase_local, 1)} %",
        "Significance - Global (% increase to MTOW)": f"{round(percentage_increase_mtow, 2)} %"
    }